name: 'Package: Lint'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  app-lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Download Homebrew Toolbox
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "webosbrew/dev-toolbox-cli"
          latest: true
          fileName: "webosbrew-toolbox-*.deb"
          out-file-path: "temp"

      - name: Install dependencies
        run: |
          python3 -m pip install -r ./requirements.txt
          sudo apt-get install ./temp/webosbrew-toolbox-*.deb

      - name: Check changed packages
        id: changed_files
        uses: dorny/paths-filter@v3
        with:
          list-files: shell
          filters: |
            packages:
              - added|modified: 'packages/**'

      - name: Lint package information
        if: ${{ steps.changed_files.outputs.packages == 'true' }}
        run: |
          export lint_retcode=0
          for changed_file in ${{ steps.changed_files.outputs.packages_files }}; do
            echo "## Check Results for $(basename "${changed_file}"):" >> /tmp/lint-report.md
            echo >> /tmp/lint-report.md

            echo '### Metadata Lint Result' >> /tmp/lint-report.md
            echo >> /tmp/lint-report.md

            python3 -m repogen.lintpkg -f "${changed_file}" >> /tmp/lint-report.md || export lint_retcode=1
            echo >> /tmp/lint-report.md

            ipkfile=/tmp/$(sha256sum "${changed_file}" | cut -d ' ' -f 1).ipk
            python3 -m repogen.downloadipk -i "${changed_file}" -o "${ipkfile}" >> /tmp/lint-report.md || { export lint_retcode=1; continue; }

            echo '### Compatibility Check Results' >> /tmp/lint-report.md

            python3 -m repogen.check_compat -i "${changed_file}" -p "${ipkfile}" >> /tmp/lint-report.md || export lint_retcode=1
          done
          exit ${lint_retcode}

      - name: Save issue number
        # Skip on act or when previous step cancelled
        if: ${{ !env.ACT && (success() || failure()) }}
        run: echo '${{ github.event.number }}' > /tmp/issue-number.txt

      - name: Upload lint results
        # Skip on act or when previous step cancelled
        if: ${{ !env.ACT && (success() || failure()) }}
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: |
            /tmp/lint-report.md
            /tmp/issue-number.txt

      - name: Print lint results (local)
        # Only run on act when previous steps not canceled 
        if: ${{ env.ACT && (success() || failure()) }}
        run: cat /tmp/lint-report.md
